import { createClient, type Session } from '@supabase/supabase-js';
import './styles.css';

const P = 'usr_nmexs7bytxq2';
const FOX = `${P}_fox_spirits`;
const FINDS = `${P}_ember_finds`;
const FOX_BUCKET = `${P}_fox_sigils`;
const WAKE_BUCKET = `${P}_awakening_sigils`;
const TILE = 24;
const W = 22;
const H = 40;
const POWER_COST = 5;
const EMBERS = [['hearth','Hearth Ember',15,5],['lullaby','Lullaby Ember',6,13],['wayfarer','Wayfarer Ember',14,18],['forge','Forge Ember',8,24],['spring','Spring Ember',17,31],['cradle','Cradle Ember',5,35]] as const;
const NPCS = [['bear','The Old Bear',5,6,'#7a563f'],['traveler','The Lost Traveler',12,21,'#d7f0ff'],['sprite','The Aurora Sprite',15,34,'#91ffe7']] as const;
const MONSTERS = [['moth','Rime Moth',17,11,0,2,'#9fffe8'],['wisp','Cinder Wisp',4,20,1,4,'#ff9f43'],['stag','Hollow Stag',16,30,2,6,'#ff73ca']] as const;
const BLOCKS = new Set(['2,4','3,5','9,4','16,4','19,7','4,10','10,10','18,12','2,15','7,16','15,16','20,18','3,22','18,23','6,27','12,28','20,29','3,33','11,35','18,36','10,5','4,7','18,8','5,18','15,24','7,32','12,33','17,34','14,36', ...NPCS.map((n) => `${n[2]},${n[3]}`)]);
for (let i = 0; i < 8; i++) BLOCKS.add(`${7 + i},${24 + (i % 2)}`);

type Dir = 'up' | 'down' | 'left' | 'right';
type View = 'hollow' | 'codex' | 'awakened';
type Profile = { user_id: string; display_name: string; sigil_path: string; current_x: number; current_y: number; embers_collected: string[]; npcs_talked_to: string[]; monsters_defeated: string[]; xp: number; power_level: number; awakened_at: string | null; awakening_sigil_path: string | null };
type Target = { kind: 'npc' | 'ember' | 'monster'; id: string; label: string } | null;
type Ghost = { user_id: string; display_name: string; sigil_path: string; x: number; y: number; last: number };
declare global { interface Window { __cinder?: { state: () => object; move: (dir: Dir) => Promise<void>; interact: () => Promise<void>; setPosition: (x: number, y: number) => void; refreshProfile: () => Promise<void> } } }

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true } });

class App {
  private root = document.querySelector<HTMLDivElement>('#app')!;
  private canvas?: HTMLCanvasElement;
  private ctx?: CanvasRenderingContext2D;
  private session: Session | null = null;
  private profile: Profile | null = null;
  private view: View = 'hollow';
  private authMode: 'up' | 'in' = 'up';
  private loadingAuth = false;
  private pos = { x: 11, y: 4 };
  private from = { x: 11, y: 4 };
  private to = { x: 11, y: 4 };
  private moving = false;
  private stepAt = 0;
  private facing: Dir = 'down';
  private cameraY = 0;
  private lastSave = 0;
  private joyPointer: number | null = null;
  private joyDir: Dir | null = null;
  private joyTimer: number | null = null;
  private particles: { x: number; y: number; vx: number; vy: number; life: number; color: string }[] = [];
  private snow = Array.from({ length: 95 }, () => ({ x: Math.random() * innerWidth, y: Math.random() * innerHeight, z: .4 + Math.random() * 1.4 }));
  private ghosts = new Map<string, Ghost>();
  private wakeAt = 0;

  async start() { this.session = (await supabase.auth.getSession()).data.session; supabase.auth.onAuthStateChange((_event, session) => { this.session = session; void this.boot(); }); if (this.session) await this.boot(); else this.renderAuth(); }
  private async boot() { if (!this.session?.user) { this.renderAuth(); return; } let profile = await this.loadProfile(); if (!profile) { await this.createProfile(this.session.user.id, String(this.session.user.user_metadata?.display_name || 'Fox Spirit')); profile = await this.loadProfile(); } if (!profile) return; this.profile = profile; this.pos = { x: profile.current_x, y: profile.current_y }; this.from = { ...this.pos }; this.to = { ...this.pos }; this.renderGame(); this.realtime(); window.__cinder = { state: () => ({ position: this.pos, profile: this.profile, target: this.target(), ghosts: [...this.ghosts.values()], particles: this.particles.length }), move: (dir) => this.move(dir), interact: () => this.interact(), setPosition: (x, y) => { this.pos = { x, y }; this.from = { x, y }; this.to = { x, y }; }, refreshProfile: () => this.refresh() }; requestAnimationFrame((t) => this.frame(t)); }
  private renderAuth(message = '') { this.root.innerHTML = `<main class="auth-screen"><section class="auth-card"><h1 class="brand">Cinderwhisp Hollow</h1><p class="subtitle">A fox spirit adventure under aurora-lit pines. Gather Ember Memories and wake winter's hearth.</p><div class="auth-tabs"><button data-mode="up" class="${this.authMode === 'up' ? 'active' : ''}" ${this.loadingAuth ? 'disabled' : ''}>Sign up</button><button data-mode="in" class="${this.authMode === 'in' ? 'active' : ''}" ${this.loadingAuth ? 'disabled' : ''}>Sign in</button></div><form id="authForm" class="form"><label class="${this.authMode === 'in' ? 'hidden' : ''}">Display name<input name="displayName" autocomplete="nickname" maxlength="18"></label><label>Email<input name="email" type="email" autocomplete="email" inputmode="email" autocapitalize="none" required></label><label>Password<input name="password" type="password" autocomplete="${this.authMode === 'up' ? 'new-password' : 'current-password'}" minlength="6" required></label><button class="primary" ${this.loadingAuth ? 'disabled' : ''}>${this.loadingAuth ? `<span class="spinner"></span>${this.authMode === 'up' ? 'Signing up…' : 'Signing in…'}` : this.authMode === 'up' ? 'Begin the hush' : 'Return to the hollow'}</button><div class="error">${message}</div></form></section></main>`; this.root.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach((b) => b.onclick = () => { if (!this.loadingAuth) { this.authMode = b.dataset.mode === 'in' ? 'in' : 'up'; this.renderAuth(); } }); this.root.querySelector<HTMLFormElement>('#authForm')!.onsubmit = (event) => { event.preventDefault(); const f = new FormData(event.currentTarget as HTMLFormElement); void this.submit(String(f.get('email')), String(f.get('password')), String(f.get('displayName') || 'Fox Spirit')); }; }
  private async submit(email: string, password: string, displayName: string) { if (this.loadingAuth) return; this.loadingAuth = true; this.renderAuth(); if (this.authMode === 'in') { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { this.loadingAuth = false; this.renderAuth(error.message); } return; } const cleanName = displayName.trim().slice(0, 18) || 'Fox Spirit'; const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: cleanName } } }); if (error || !data.user) { this.loadingAuth = false; this.renderAuth(error?.message || 'Sign-up did not return a user.'); return; } this.session = data.session ?? (await supabase.auth.getSession()).data.session; if (!this.session) { this.loadingAuth = false; this.authMode = 'in'; this.renderAuth('Check your email if confirmation is enabled, then sign in.'); return; } await this.createProfile(data.user.id, cleanName); await this.boot(); }
  private async createProfile(userId: string, displayName: string) { const path = `${userId}/sigil.png`; const upload = await supabase.storage.from(FOX_BUCKET).upload(path, await sigilBlob(userId, 'fox'), { contentType: 'image/png', upsert: true }); if (upload.error) throw upload.error; const sigil_path = supabase.storage.from(FOX_BUCKET).getPublicUrl(path).data.publicUrl; await supabase.from(FOX).upsert({ user_id: userId, display_name: displayName, sigil_path, current_x: 11, current_y: 4, embers_collected: [], npcs_talked_to: [], monsters_defeated: [], xp: 0, power_level: 0 }, { onConflict: 'user_id' }); }
  private async loadProfile() { const uid = this.session?.user.id; if (!uid) return null; const { data, error } = await supabase.from(FOX).select('*').eq('user_id', uid).maybeSingle(); if (error) throw error; return data as Profile | null; }
  private async refresh() { const profile = await this.loadProfile(); if (profile) { this.profile = profile; this.hud(); } }
  private renderGame() { this.root.innerHTML = `<main class="shell"><section class="game"><canvas id="gameCanvas"></canvas><div class="hud"><div class="player-pill"><img id="avatar"><div><div class="player-name"></div><button class="sign-out">sign out</button></div></div><div class="stat-pill"></div></div><div class="toast-stack"></div><button class="power-shop">Buy Power · 5 XP</button><div class="joystick"><div class="joystick-ring"><div class="joystick-knob"></div></div></div><button class="interact hidden">Talk</button><div class="dialogue hidden"><img><p></p><button>…</button></div><div class="epitaph hidden">What we remember, we carry.</div></section><section class="panel hidden" id="codexPanel"><header><h2>Memory Codex</h2></header><div class="scroll"></div></section><section class="panel hidden" id="awakenedPanel"><header><h2>Awakened</h2></header><div class="scroll"></div></section><nav class="nav"><button data-view="hollow">Hollow</button><button data-view="codex">Memory Codex</button><button data-view="awakened">Awakened</button></nav></main>`; this.canvas = this.root.querySelector('#gameCanvas')!; this.ctx = this.canvas.getContext('2d')!; this.resize(); addEventListener('resize', () => this.resize()); addEventListener('keydown', (e) => this.key(e)); this.root.querySelector<HTMLButtonElement>('.sign-out')!.onclick = () => void supabase.auth.signOut(); this.root.querySelector<HTMLButtonElement>('.interact')!.onclick = () => void this.interact(); this.root.querySelector<HTMLButtonElement>('.power-shop')!.onclick = () => void this.buyPower(); this.root.querySelector<HTMLButtonElement>('.dialogue button')!.onclick = () => this.root.querySelector('.dialogue')?.classList.add('hidden'); this.root.querySelectorAll<HTMLButtonElement>('[data-view]').forEach((b) => b.onclick = () => void this.show(b.dataset.view as View)); this.joystick(); this.hud(); void this.show('hollow'); }
  private resize() { if (!this.canvas) return; const dpr = Math.min(devicePixelRatio || 1, 3); this.canvas.width = innerWidth * dpr; this.canvas.height = innerHeight * dpr; this.ctx?.setTransform(dpr, 0, 0, dpr, 0, 0); }
  private hud() { if (!this.profile) return; this.root.querySelector<HTMLImageElement>('#avatar')!.src = this.profile.sigil_path; this.root.querySelector('.player-name')!.textContent = this.profile.display_name; this.root.querySelector('.stat-pill')!.textContent = `🔥 ${this.profile.embers_collected.length} / 6  ✦ Lv ${Math.floor(this.profile.xp / 10) + 1}  ⚔ ${this.profile.power_level}`; }
  private async show(view: View) { this.view = view; this.root.querySelector('.game')?.classList.toggle('hidden', view !== 'hollow'); this.root.querySelector('#codexPanel')?.classList.toggle('hidden', view !== 'codex'); this.root.querySelector('#awakenedPanel')?.classList.toggle('hidden', view !== 'awakened'); this.root.querySelectorAll<HTMLButtonElement>('[data-view]').forEach((b) => b.classList.toggle('active', b.dataset.view === view)); if (view === 'codex') await this.codex(); if (view === 'awakened') await this.awakened(); }
  private joystick() { const j = this.root.querySelector<HTMLElement>('.joystick')!, k = this.root.querySelector<HTMLElement>('.joystick-knob')!; const end = () => { this.joyPointer = null; this.joyDir = null; if (this.joyTimer) clearInterval(this.joyTimer); this.joyTimer = null; k.style.transform = 'translate(-50%, -50%)'; }; const update = (e: PointerEvent) => { if (this.joyPointer !== e.pointerId) return; e.preventDefault(); const r = j.getBoundingClientRect(), dx = e.clientX - (r.left + r.width / 2), dy = e.clientY - (r.top + r.height / 2), d = Math.min(34, Math.hypot(dx, dy)), a = Math.atan2(dy, dx); k.style.transform = `translate(calc(-50% + ${Math.cos(a) * d}px), calc(-50% + ${Math.sin(a) * d}px))`; this.joyDir = d < 10 ? null : Math.abs(dx) > Math.abs(dy) ? dx > 0 ? 'right' : 'left' : dy > 0 ? 'down' : 'up'; }; j.onpointerdown = (e) => { e.preventDefault(); this.joyPointer = e.pointerId; j.setPointerCapture(e.pointerId); update(e); if (this.joyDir) void this.move(this.joyDir); this.joyTimer = window.setInterval(() => { if (this.joyDir) void this.move(this.joyDir); }, 145); }; j.onpointermove = update; j.onpointerup = end; j.onpointercancel = end; j.oncontextmenu = (e) => e.preventDefault(); j.ondblclick = (e) => e.preventDefault(); }
  private key(e: KeyboardEvent) { const d = e.key === 'ArrowUp' || e.key === 'w' ? 'up' : e.key === 'ArrowDown' || e.key === 's' ? 'down' : e.key === 'ArrowLeft' || e.key === 'a' ? 'left' : e.key === 'ArrowRight' || e.key === 'd' ? 'right' : null; if (d) { e.preventDefault(); void this.move(d); } if (e.key === 'e' || e.key === ' ') { e.preventDefault(); void this.interact(); } }
  private async move(dir: Dir) { if (this.moving || this.view !== 'hollow') return; this.facing = dir; const [dx, dy] = dir === 'up' ? [0, -1] : dir === 'down' ? [0, 1] : dir === 'left' ? [-1, 0] : [1, 0], nx = this.pos.x + dx, ny = this.pos.y + dy; const monster = MONSTERS.find((m) => m[2] === nx && m[3] === ny && !this.profile?.monsters_defeated.includes(m[0])); if (nx < 1 || nx >= W - 1 || ny < 2 || ny >= H - 1 || BLOCKS.has(`${nx},${ny}`) || monster) return this.puff(this.pos.x, this.pos.y, '#cfe7f5', 5); this.from = { ...this.pos }; this.to = { x: nx, y: ny }; this.stepAt = performance.now(); this.moving = true; await wait(120); this.pos = { ...this.to }; this.moving = false; this.updateInteract(); if (performance.now() - this.lastSave > 1000 && this.profile) { this.lastSave = performance.now(); void supabase.from(FOX).update({ current_x: nx, current_y: ny, last_active_at: new Date().toISOString() }).eq('user_id', this.profile.user_id); } }
  private target(): Target { if (!this.profile) return null; const near = (x: number, y: number) => Math.abs(this.pos.x - x) + Math.abs(this.pos.y - y) <= 1; const ember = EMBERS.find((e) => near(e[2], e[3]) && !this.profile!.embers_collected.includes(e[0])); if (ember) return { kind: 'ember', id: ember[0], label: 'Thaw' }; const monster = MONSTERS.find((m) => near(m[2], m[3]) && !this.profile!.monsters_defeated.includes(m[0])); if (monster) return { kind: 'monster', id: monster[0], label: 'Fight' }; const npc = NPCS.find((n) => near(n[2], n[3])); if (npc) return { kind: 'npc', id: npc[0], label: npc[0] === 'bear' && this.profile.embers_collected.length >= 6 ? 'Awaken' : 'Talk' }; return null; }
  private updateInteract() { const t = this.target(), b = this.root.querySelector<HTMLButtonElement>('.interact'); if (!b) return; b.classList.toggle('hidden', !t); if (t) b.textContent = t.label; }
  private async interact() { const t = this.target(); if (!t || !this.profile) return; if (t.kind === 'ember') return this.thaw(t.id); if (t.kind === 'monster') return this.fight(t.id); if (t.id === 'bear' && t.label === 'Awaken') return this.awaken(); return this.talk(t.id); }
  private async buyPower() { if (!this.profile) return; if (this.profile.xp < POWER_COST) return this.toast('Earn 5 XP to buy foxfire power.'); const xp = this.profile.xp - POWER_COST, power_level = this.profile.power_level + 1; const { error } = await supabase.from(FOX).update({ xp, power_level }).eq('user_id', this.profile.user_id); if (error) return this.toast(error.message); this.profile = { ...this.profile, xp, power_level }; this.hud(); this.toast(`Foxfire power increased to ${power_level}.`); vibrate(20); }
  private async fight(id: string) { if (!this.profile) return; const m = MONSTERS.find((x) => x[0] === id); if (!m) return; if (this.profile.power_level < m[4]) return this.toast(`${m[1]} needs ⚔ ${m[4]}. Buy power with XP first.`); const monsters_defeated = [...this.profile.monsters_defeated, m[0]], xp = this.profile.xp + m[5]; const { error } = await supabase.from(FOX).update({ monsters_defeated, xp }).eq('user_id', this.profile.user_id); if (error) return this.toast(error.message); this.profile = { ...this.profile, monsters_defeated, xp }; this.puff(m[2], m[3], m[6], 18); this.hud(); this.toast(`${m[1]} faded. +${m[5]} XP`); vibrate([15,25,15]); }
  private async thaw(id: string) { if (!this.profile) return; const ember = EMBERS.find((e) => e[0] === id)!; const { error } = await supabase.from(FINDS).insert({ ember_id: id, finder_user_id: this.profile.user_id, display_name: this.profile.display_name }); if (error) return this.toast(error.code === '23505' ? `${ember[1]} already remembers you.` : error.message); this.puff(ember[2], ember[3], '#ffbd57', 18); vibrate(30); await wait(260); await this.refresh(); }
  private async talk(id: string) { if (!this.profile) return; if (!this.profile.npcs_talked_to.includes(id)) { const npcs_talked_to = [...this.profile.npcs_talked_to, id], xp = this.profile.xp + 1; await supabase.from(FOX).update({ npcs_talked_to, xp }).eq('user_id', this.profile.user_id); this.profile = { ...this.profile, npcs_talked_to, xp }; this.hud(); } const text = id === 'bear' ? 'Six Embers slumber in the snow, little one. Bring them to my hearth and the winter will remember spring.' : id === 'traveler' ? 'Two Embers shelter where the birches lean inward — beneath roots, beside the broken bridge.' : 'The brightest sleep where the sky touches the ground. The ribbons remember.'; this.dialogue(id, text); vibrate([10,30,10]); }
  private async awaken() { if (!this.profile) return; await this.refresh(); if (!this.profile || this.profile.embers_collected.length < 6) return this.toast('The hearth waits for all six Embers.'); const path = `${this.profile.user_id}/awakening.png`; await supabase.storage.from(WAKE_BUCKET).upload(path, await sigilBlob(`${this.profile.user_id}:${this.profile.embers_collected.join(',')}`, 'awakening'), { contentType: 'image/png', upsert: true }); const awakening_sigil_path = supabase.storage.from(WAKE_BUCKET).getPublicUrl(path).data.publicUrl; await supabase.from(FOX).update({ awakened_at: new Date().toISOString(), awakening_sigil_path }).eq('user_id', this.profile.user_id).is('awakened_at', null); this.wakeAt = performance.now(); this.root.querySelector('.epitaph')?.classList.remove('hidden'); vibrate([20,40,20,40]); await this.refresh(); }
  private dialogue(seed: string, text: string) { const d = this.root.querySelector<HTMLElement>('.dialogue')!; d.querySelector('img')!.src = sigilUrl(seed, 'portrait'); d.querySelector('p')!.textContent = text; d.classList.remove('hidden'); }
  private realtime() { if (!this.profile) return; const ch = supabase.channel('foxes_in_hollow', { config: { broadcast: { self: false, ack: true } } }).on('broadcast', { event: 'position' }, ({ payload }) => { const g = payload as Ghost; if (g.user_id !== this.profile?.user_id) this.ghosts.set(g.user_id, { ...g, last: performance.now() }); }).subscribe(); supabase.channel('ember-finds-feed').on('postgres_changes', { event: 'INSERT', schema: 'public', table: FINDS }, (p) => { const row = p.new as { display_name: string; ember_id: string }; this.toast(`✦ ${row.display_name} thawed the ${EMBERS.find((e) => e[0] === row.ember_id)?.[1] || row.ember_id}`); void this.refresh(); }).subscribe(); setInterval(() => { if (this.profile) void ch.send({ type: 'broadcast', event: 'position', payload: { user_id: this.profile.user_id, display_name: this.profile.display_name, sigil_path: this.profile.sigil_path, x: this.pos.x, y: this.pos.y } }); }, 2000); }
  private async codex() { const host = this.root.querySelector('#codexPanel .scroll')!; const { data } = await supabase.rpc(`${P}_codex`); const rows = (data || []) as { ember_id: string; display_name: string; found_at: string; sigil_path: string }[]; host.innerHTML = rows.length ? EMBERS.map((e) => `<section class="group"><h3>${e[1]}</h3>${rows.filter((r) => r.ember_id === e[0]).map((r) => `<article class="card"><img src="${r.sigil_path}" loading="lazy"><div><strong>${safe(r.display_name)}</strong><span>${new Date(r.found_at).toLocaleString()}</span></div></article>`).join('') || '<div class="card">Still frozen</div>'}</section>`).join('') : '<div class="empty">No Ember Memories yet.</div>'; }
  private async awakened() { const host = this.root.querySelector('#awakenedPanel .scroll')!; const { data } = await supabase.rpc(`${P}_awakened`); const rows = (data || []) as { display_name: string; awakened_at: string; awakening_sigil_path: string }[]; host.innerHTML = rows.length ? `<div class="hall">${rows.map((r) => `<article class="card"><img src="${r.awakening_sigil_path}" loading="lazy"><strong>${safe(r.display_name)}</strong><span>${new Date(r.awakened_at).toLocaleDateString()}</span></article>`).join('')}</div>` : '<div class="empty">No hearth has awakened yet.</div>'; }
  private frame(time: number) { this.draw(time); this.updateInteract(); requestAnimationFrame((t) => this.frame(t)); }
  private draw(time: number) { if (!this.ctx || !this.profile) return; const c = this.ctx, w = innerWidth, h = innerHeight, py = this.screen().y; if (py - this.cameraY < h * .38) this.cameraY = Math.max(0, py - h * .38); if (py - this.cameraY > h * .58) this.cameraY = Math.min(H * TILE - h + 90, py - h * .58); const sky = c.createLinearGradient(0,0,0,h); sky.addColorStop(0,'#081436'); sky.addColorStop(1,'#06101d'); c.fillStyle = sky; c.fillRect(0,0,w,h); for (let i=0;i<4;i++){c.strokeStyle=`hsla(${(time/80+i*80)%360},92%,68%,.23)`; c.lineWidth=18+i*6; c.beginPath(); for(let x=-30;x<w+30;x+=18){const y=70+i*30+Math.sin(x*.018+time*.0008+i)*24; if(x===-30)c.moveTo(x,y); else c.lineTo(x,y)} c.stroke()} c.save(); c.translate((w - W*TILE)/2, -this.cameraY + 52); for (let y=0;y<H;y++){c.fillStyle=y<13?'#b7cede':y<27?'#9eb8ca':'#bad8df'; c.fillRect(0,y*TILE,W*TILE,TILE)} EMBERS.forEach((e)=>this.lantern(c,e[2]*TILE,e[3]*TILE,this.profile!.embers_collected.includes(e[0])||this.wakeAt>0,time)); BLOCKS.forEach((v)=>{const [x,y]=v.split(',').map(Number); this.pine(c,x*TILE,y*TILE)}); NPCS.forEach((n)=>this.npc(c,n[2]*TILE,n[3]*TILE,n[4],time)); MONSTERS.forEach((m)=>{ if(!this.profile!.monsters_defeated.includes(m[0])) this.monster(c,m[2]*TILE,m[3]*TILE,m[6],time,m[4])}); [...this.ghosts.values()].forEach((g)=>{ if(performance.now()-g.last>10000)return this.ghosts.delete(g.user_id); c.globalAlpha=.6; this.fox(c,g.x*TILE,g.y*TILE,time,'down'); c.globalAlpha=1; c.fillStyle='#dff8ff'; c.font='10px Space Mono'; c.textAlign='center'; c.fillText(g.display_name,g.x*TILE+12,g.y*TILE-4)}); const p=this.screen(); this.fox(c,p.x,p.y,time,this.facing); this.particles=this.particles.filter((p)=>{p.life-=16;p.x+=p.vx;p.y+=p.vy;c.globalAlpha=Math.max(0,p.life/800);c.fillStyle=p.color;c.fillRect(p.x,p.y,3,3);c.globalAlpha=1;return p.life>0}); c.restore(); this.snow.forEach((s)=>{s.y+=s.z*1.2; if(s.y>h){s.y=-5;s.x=Math.random()*w} c.fillStyle='rgba(244,251,255,.65)'; c.beginPath(); c.arc(s.x,s.y,s.z*1.5,0,Math.PI*2); c.fill()}); }
  private screen(){ if(!this.moving) return {x:this.pos.x*TILE,y:this.pos.y*TILE}; const t=Math.min(1,(performance.now()-this.stepAt)/120); return {x:(this.from.x+(this.to.x-this.from.x)*t)*TILE,y:(this.from.y+(this.to.y-this.from.y)*t)*TILE}; }
  private fox(c: CanvasRenderingContext2D,x:number,y:number,time:number,dir:Dir){void dir;c.shadowColor='#ffb347';c.shadowBlur=14;c.fillStyle='#ffb347';c.beginPath();c.ellipse(x+12,y+13,8,7,0,0,Math.PI*2);c.fill();c.fillStyle='#fff1c2';c.fillRect(x+9,y+10,2,2);c.fillRect(x+14,y+10,2,2);c.fillStyle='#f07d2e';c.fillRect(x+3+(Math.floor(time/120)%2),y+14,7,4);c.shadowBlur=0}
  private pine(c: CanvasRenderingContext2D,x:number,y:number){c.fillStyle='#0f4b4d';c.beginPath();c.moveTo(x+12,y);c.lineTo(x+2,y+21);c.lineTo(x+22,y+21);c.fill();c.fillStyle='#d8edf6';c.fillRect(x+5,y+10,13,2)}
  private npc(c: CanvasRenderingContext2D,x:number,y:number,color:string,time:number){c.fillStyle=color;c.beginPath();c.ellipse(x+12,y+13,9,9,0,0,Math.PI*2);c.fill();c.fillStyle=`hsl(${time/18%360},90%,72%)`;c.fillRect(x+8,y+8,3,3);c.fillRect(x+14,y+8,3,3)}
  private monster(c: CanvasRenderingContext2D,x:number,y:number,color:string,time:number,power:number){c.save();c.translate(0,Math.sin(time/220+x)*2);c.shadowColor=color;c.shadowBlur=12;c.fillStyle='rgba(10,16,34,.78)';c.beginPath();c.ellipse(x+12,y+14,10,9,0,0,Math.PI*2);c.fill();c.strokeStyle=color;c.lineWidth=2;c.beginPath();c.arc(x+12,y+14,10+power*2,0,Math.PI*2);c.stroke();c.fillStyle=color;c.fillRect(x+7,y+8,3,3);c.fillRect(x+14,y+8,3,3);c.restore()}
  private lantern(c:CanvasRenderingContext2D,x:number,y:number,lit:boolean,time:number){c.fillStyle='#dce9f4';c.fillRect(x+7,y+13,10,5);c.fillStyle=lit?'#ffb347':'#8ca9bb';c.fillRect(x+9,y+8,6,8); if(lit){c.globalAlpha=.4+Math.sin(time/180)*.18;c.fillStyle='#ffd58a';c.beginPath();c.arc(x+12,y+12,12,0,Math.PI*2);c.fill();c.globalAlpha=1}}
  private puff(x:number,y:number,color:string,count:number){for(let i=0;i<count;i++)this.particles.push({x:x*TILE+12,y:y*TILE+12,vx:(Math.random()-.5)*4,vy:(Math.random()-.8)*4,life:700,color})}
  private toast(text:string){const el=document.createElement('div');el.className='toast';el.textContent=text;this.root.querySelector('.toast-stack')?.appendChild(el);setTimeout(()=>el.remove(),3400)}
}
function sigilUrl(seed:string, kind:string){return sigil(seed,kind).toDataURL('image/png')} function sigilBlob(seed:string, kind:string){return new Promise<Blob>((resolve)=>sigil(seed,kind).toBlob((b)=>resolve(b!), 'image/png'))} function sigil(seed:string, kind:string){const c=document.createElement('canvas'),x=c.getContext('2d')!,r=rand(hash(seed+kind));c.width=32;c.height=32;x.fillStyle='#f2dfbd';x.fillRect(0,0,32,32);for(let i=0;i<12;i++){x.fillStyle=['#87b8cc','#233d65','#9fffe8','#ff9f43'][Math.floor(r()*4)];const a=Math.floor(r()*16),b=Math.floor(r()*16),s=3+Math.floor(r()*8);x.fillRect(a,b,s,s);x.fillRect(31-a-s,b,s,s);x.fillRect(a,31-b-s,s,s);x.fillRect(31-a-s,31-b-s,s,s)}return c}
function hash(v:string){let h=2166136261;for(let i=0;i<v.length;i++)h=Math.imul(h^v.charCodeAt(i),16777619);return h>>>0} function rand(s:number){return()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}} function wait(ms:number){return new Promise((r)=>setTimeout(r,ms))} function vibrate(p:VibratePattern){if('vibrate'in navigator)navigator.vibrate(p)} function safe(v:string){return v.replace(/[&<>"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!))}
void new App().start();
